### ISSUE TITLE
Ns-vue-loader is not a valid NativeScript plugin

### ISSUE THREAD

**Issue by xeroxstar** [tralves/ns-vue-loader#5]
Hello, i tried your plugin but after i run `**'tns plugin add ns-vue-loader'**` i get an error:
`ns-vue-loader is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.`

**Comment by tralves** [comment]
Hi!

This is not a NativeScript plugin per se. It is a webpack module used to bundle `.vue` files in a way that they are usable by NativeScript.

This project is used, for instance, in [`vue-cli-template`](https://github.com/nativescript-vue/vue-cli-template/) webpack configuration. You probably don't need to install it yourself.

**Comment by xeroxstar** [comment]
Thx Tralves, the problem was is that i started my first app with the wrong template. After i tried vue-cli-template , everything is working 👍
